drop table if exists cdm.dm_courier_ledger;
create table cdm.dm_courier_ledger(
id integer generated by default as identity primary key,
courier_id integer not null,
courier_name varchar not null,
settlement_year integer not null constraint courier_ledger_year_check check(((settlement_year >= 2022) AND (settlement_year < 2500))),
settlement_month integer not null constraint courier_ledger_month_check check(((settlement_month >= 1) AND (settlement_month <= 12))),
orders_count integer not null constraint courier_ledger_count_check check(orders_count>0),
orders_total_sum decimal(14,2) not null constraint courier_ledger_sum_check check(orders_total_sum>0),
rate_avg decimal(14,1) not null constraint courier_ledger_rate_check check(rate_avg>=1 and rate_avg<=5),
order_processing_fee decimal(14,2) not null constraint processing_fee_check check(order_processing_fee>0),
courier_order_sum decimal(14,2) not null constraint courier_sum_check check(courier_order_sum>0),
courier_tips_sum decimal(14,2) not null constraint tips_sum_check check(courier_tips_sum>0),
courier_reward_sum decimal(14,2) not null constraint reward_sum_check check(courier_reward_sum>0)
);
alter table cdm.dm_courier_ledger add constraint un_key_cl unique(courier_id, settlement_year, settlement_month);